apiVersion: batch/v1
kind: CronJob
metadata:
  name: new-bb-programs-notification
  namespace: bb
spec:
  schedule: "*/5 * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            project: bb
          containers:
          - name: new-bb-programs-notification
            image: MY-REGISTRY/new-bb-programs-notification:latest
            env:
              - name: BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: telegram-secrets 
                    key: BOT_TOKEN
              - name: PERSONAL_CHAT_ID
                valueFrom:
                  secretKeyRef:
                    name: telegram-secrets 
                    key: PERSONAL_CHAT_ID
              - name: LOG_LEVEL
                value: "DEBUG"
          restartPolicy: Never
