apiVersion: batch/v1
kind: CronJob
metadata:
  name: new-bb-programs-notification
  namespace: utils
spec:
  schedule: "*/10 * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            project: utils
          imagePullSecrets:
            - name: ghcr-secret
          containers:
          - name: new-bb-programs-notification
            image: ghcr.io/jstrah00/new_bb_programs_notification:latest
            volumeMounts:
              - name: new-bb-programs-notification-state
                mountPath: /data
            env:
              - name: BOT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: telegram-secret
                    key: KOBE_BOT_TOKEN
              - name: PERSONAL_CHAT_ID
                valueFrom:
                  secretKeyRef:
                    name: telegram-secret
                    key: PERSONAL_CHAT_ID
              - name: LOG_LEVEL
                value: "DEBUG"
              - name: LAST_PROGRAM_FILE_PATH
                value: /data/last_program.txt
          volumes:
            - name: new-bb-programs-notification-state
              hostPath:
                path: /var/cronstate/new-bb-programs-notification
                type: DirectoryOrCreate
          restartPolicy: Never
