apiVersion: v1
kind: Pod
metadata:
  name: pvc-debugger
  namespace: bb
spec:
  containers:
  - name: shell
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /mnt/data
      name: debug-vol
  volumes:
  - name: debug-vol
    persistentVolumeClaim:
      claimName: new-bb-programs-notification-pvc
  restartPolicy: Never
