apiVersion: v1
kind: PersistentVolume
metadata:
  name: new-bb-programs-notification-pv
  namespace: bb
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/k3s-volumes/new_bb_programs_notification
  persistentVolumeReclaimPolicy: Retain
